### ISSUE TITLE
phosphor-gevent[805]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown:

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#1204]
Saw this one on the way to BMC_READY with our latest driver.  Maybe a service dependency issue @bradbishop ?

```
Feb 22 06:05:42 witherspoon systemd[1]: Started Phosphor Webserver.
Feb 22 06:05:57 witherspoon phosphor-gevent[805]: Traceback (most recent call last):
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/sbin/phosphor-gevent", line 35, in <module>
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     app = App()
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 690, in __init__
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     self.mapper = obmc.mapper.Mapper(self.bus)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/bindings.py", line 32, in __init__
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     obj = bus.get_object(MAPPER_NAME, MAPPER_PATH, introspect=False)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     follow_name_owner_changes=follow_name_owner_changes)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     self._named_service = conn.activate_name_owner(bus_name)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     self.start_service_by_name(bus_name)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     'su', (bus_name, flags)))
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Feb 22 06:05:57 witherspoon phosphor-gevent[805]:     message, timeout)
Feb 22 06:05:57 witherspoon phosphor-gevent[805]: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name xyz.openbmc_project.ObjectMapper was not provided by any .service files
Feb 22 06:05:57 witherspoon systemd[1]: phosphor-gevent.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 06:05:57 witherspoon systemd[1]: phosphor-gevent.service: Unit entered failed state.
Feb 22 06:05:57 witherspoon systemd[1]: phosphor-gevent.service: Failed with result 'exit-code'.
Feb 22 06:05:57 witherspoon systemd[1]: phosphor-gevent.service: Service hold-off time over, scheduling restart.
Feb 22 06:05:57 witherspoon systemd[1]: Stopped Phosphor Webserver.
Feb 22 06:05:57 witherspoon systemd[1]: Started Phosphor Webserver.
```

```
[witherspoon]# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v1.99.2-142"
VERSION_ID="v1.99.2-142-g2f30409-dirty"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v1.99.2-142"
BUILD_ID="v1.99.2"
```

**Comment by geissonator** [comment]
Brad has potential fix here - https://gerrit.openbmc-project.xyz/#/c/2703/
