### ISSUE TITLE
ipmid: mac address errors

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1243]
I saw this when booting the host on my palmetto:

`v1.99.3-32-g05b7eba` (05b7eba)

```
Mar 03 00:11:17 palmetto ipmid[782]: sscanf Failed in extracting mac address.
Mar 03 00:11:17 palmetto ipmid[782]: getHostNetworkData failed for get_sys_boot_options.
Mar 03 00:11:17 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x9]
Mar 03 00:11:17 palmetto ipmid[782]: sscanf Failed in extracting mac address.
Mar 03 00:11:17 palmetto ipmid[782]: getHostNetworkData failed for get_sys_boot_options.
Mar 03 00:11:17 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x9]
Mar 03 00:11:17 palmetto ipmid[782]: sscanf Failed in extracting mac address.
Mar 03 00:11:17 palmetto ipmid[782]: getHostNetworkData failed for get_sys_boot_options.
Mar 03 00:11:17 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x9]
Mar 03 00:11:17 palmetto ipmid[782]: sscanf Failed in extracting mac address.
Mar 03 00:11:17 palmetto ipmid[782]: getHostNetworkData failed for get_sys_boot_options.
Mar 03 00:11:17 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x9]
Mar 03 00:11:17 palmetto ipmid[782]: No registered handlers for NetFn:[0x3A], Cmd:[0x1A] trying Wilcard implementation
Mar 03 00:11:17 palmetto ipmid[782]: No Registered handlers for NetFn:[0x3A],Cmd:[0xFF]
Mar 03 00:11:17 palmetto ipmid[782]: ERROR:[0xC1] handling NetFn:[0x3A], Cmd:[0x1A]
```

```
Mar 03 00:11:27 palmetto ipmid[782]: Failed to issue method call: Traceback (most recent call last):
Mar 03 00:11:27 palmetto ipmid[782]:   File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
Mar 03 00:11:27 palmetto ipmid[782]:     retval = candidate_method(self, *args, **keywords)
Mar 03 00:11:27 palmetto ipmid[782]:   File "/usr/lib/python2.7/site-packages/obmc/dbuslib/bindings.py", line 82, in Set
Mar 03 00:11:27 palmetto ipmid[782]:     self.validator(interface_name, property_name, new_value)
Mar 03 00:11:27 palmetto ipmid[782]:   File "/usr/sbin/settings_manager.py", line 236, in input_validator
Mar 03 00:11:27 palmetto ipmid[782]:     self.validate_list(shk['allowed'], value)
Mar 03 00:11:27 palmetto ipmid[782]:   File "/usr/sbin/settings_manager.py", line 176, in validate_list
Mar 03 00:11:27 palmetto ipmid[782]:     raise ValueError("Invalid input. Data not in allowed values")
Mar 03 00:11:27 palmetto ipmid[782]: ValueError: Invalid input. Data not in allowed values
Mar 03 00:11:27 palmetto ipmid[782]: Dbus set property(boot_flags) failed for set_sys_boot_options.
Mar 03 00:11:27 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x8]
Mar 03 00:11:28 palmetto ipmid[782]: sscanf Failed in extracting mac address.
Mar 03 00:11:28 palmetto ipmid[782]: getHostNetworkData failed for get_sys_boot_options.
Mar 03 00:11:28 palmetto ipmid[782]: ERROR:[0xFF] handling NetFn:[0x0], Cmd:[0x9]
```

**Comment by tomjoseph83** [comment]
This error "sscanf Failed in extracting mac address." is thrown when the MAC address is not in the expected format. Could you mention the palmetto where this was tried?

**Comment by geissonator** [comment]
So you need a fw_printenv from the palmetto showing this issue Tom?

**Comment by tomjoseph83** [comment]
@geissonator Can we get this closed, since there is no debug to do further.

**Comment by dkodihal** [comment]
Ratan is going to fix this as part of some the network manager refactor.

**Comment by dkodihal** [comment]
Same as #556 as per @ratagupt.
