### ISSUE TITLE
User unable to boot host

### ISSUE THREAD

**Issue by shenki** [openbmc/openbmc#1281]
After some use, users have reported they are unable to boot the host:

`v1.99.2-91-g1562bbc-dirty`

```
root@w8:~# obmcutil poweroff
Traceback (most recent call last):
 File "/usr/sbin/obmcutil", line 159, in <module>
   bus = dbus.SystemBus()
 File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 194, in __new__
   private=private)
 File "/usr/lib/python2.7/site-packages/dbus/_dbus.py", line 100, in __new__
   bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
 File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 122, in __new__
   bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.LimitsExceeded: The maximum number of active connections for UID 0 has been reached
```

[w8-journal.txt](https://github.com/openbmc/openbmc/files/829924/w8-journal.txt)

**Comment by williamspatrick** [comment]
That version is ancient and we fixed a number of dbus issues since then.  Is this still an issue?
