### ISSUE TITLE
BMC failed to boot to Standby [ Witherspoon ]

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#1391]
```
- [x] SYSTEM     : W42 ( Witherspoon - 2 Sockets - 16 DIMMs )
- [x] BUILD_ID   : https://openpower.xyz/job/openbmc-build/659/
- [x] VERSION_ID : v1.99.3-147-g49fe17d
- [x] Kernel     : Linux witherspoon 4.7.10-382872843bb8e7755fddeaaa284a00c640bfc732 #1 Mon Mar 27 21:26:19 UTC 2017 armv6l GNU/Linux
Test Ran

- [x] BMC update        : FAILED  ( 1 witherspoon system )
```
```
root@witherspoon:~# obmcutil state
CurrentBMCState:    xyz.openbmc_project.State.BMC.BMCState.NotReady
CurrentPowerState:  xyz.openbmc_project.State.Chassis.PowerState.Off
CurrentHostState:   xyz.openbmc_project.State.Host.HostState.Off
root@witherspoon:~# uptime
 19:00:25 up 5 min,  load average: 1.56, 1.76, 0.88
root@witherspoon:~#
```

```
root@witherspoon:~# systemctl status org.openbmc.Sensors.service | cat
● org.openbmc.Sensors.service - Phosphor Sensor Manager
   Loaded: loaded (/lib/systemd/system/org.openbmc.Sensors.service; enabled; vendor preset: enabled)
   Active: activating (start) since Tue 2017-01-31 20:35:40 UTC; 2s ago
 Main PID: 5459 (python)
   CGroup: /system.slice/org.openbmc.Sensors.service
           ‣ 5459 [python]

Jan 31 20:35:40 witherspoon systemd[1]: org.openbmc.Sensors.service: Service hold-off time over, scheduling restart.
Jan 31 20:35:40 witherspoon systemd[1]: Stopped Phosphor Sensor Manager.
Jan 31 20:35:40 witherspoon systemd[1]: Starting Phosphor Sensor Manager...
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]: Traceback (most recent call last):
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]:   File "/usr/sbin/sensor_manager2.py", line 58, in <module>
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]:     sensor_obj = getattr(obmc.sensors, sensor_class)(bus, obj_path)
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]:   File "/usr/lib/python2.7/site-packages/obmc/sensors.py", line 302, in __init__
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]:     super(PsRedundancySensor,self).setValue("Disabled")
Jan 31 20:35:43 witherspoon sensor_manager2.py[5459]: NameError: global name 'PsRedundancySensor' is not defined
root@witherspoon:~# 
```

- [x] Journald 
[journald_v1.99.3-147-g49fe17d_sensor.txt](https://github.com/openbmc/openbmc/files/874785/journald_v1.99.3-147-g49fe17d_sensor.txt)

**Comment by gkeishin** [comment]
Will verify once the builds come in.. For now the patch worked on the system
