### ISSUE TITLE
OCC PassThrough commands Timeout Error 

### ISSUE THREAD

**Issue by essawy** [openbmc/openbmc#1700]
timeout error occurs when I send occ pass through commands back to back (after getting responses and processing them). 

I got the following error in the son response
```
{u'data': {u'description': u'Internal Server Error',
  u'exception': u"DBusException('Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.',)",
  u'traceback': [u'Traceback (most recent call last):',
   u'  File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle',
   u'    return route.call(**args)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 618, in __call__',
   u'    return self.callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 675, in wrap',
   u'    return callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 853, in __call__',
   u'    return self.callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 827, in wrap',
   u'    return self.to_jsonp(callback(*a, **kw))',
   u'  File "/usr/lib/python2.7/site-packages/bottle.py", line 1734, in wrapper',
   u'    rv = callback(*a, **ka)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 792, in wrap',
   u'    data = callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 726, in wrap',
   u'    return callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 757, in wrap',
   u'    return callback(*a, **kw)',
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 103, in __call__',
   u"    return getattr(self, 'do_' + request.method.lower())(**kw)",
   u'  File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 238, in do_post',
   u"    return request.route_data['method'](*request.parameter_list)",
   u'  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__',
   u'    **keywords)',
   u'  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking',
   u'    message, timeout)',
   u'DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.']},
 u'message': u'500 Internal Server Error',
 u'status': u'error'}
```
I found this error in the BMC journal:
```
Apr 20 22:46:37 witherspoon ipmid[921]: Data: 0x592742AA]
Apr 20 22:46:37 witherspoon ipmid[921]: Error [Permission denied] setting time
Apr 20 22:46:37 witherspoon ipmid[921]: IPMI Handling GET-SEL-TIME
Apr 20 22:46:37 witherspoon ipmid[921]: Host Time read:[Thu Apr 20 22:23:24 2017 GMT] :: [1492727004]
Apr 20 22:46:37 witherspoon ipmid[921]: Handling Set-SEL-Time:[0xA], Cmd:[0x49]
Apr 20 22:46:37 witherspoon ipmid[921]: Data: 0x59274563]
Apr 20 22:46:37 witherspoon ipmid[921]: Error [Permission denied] setting time
Apr 20 22:46:37 witherspoon ipmid[921]: IPMI Handling GET-SEL-TIME
Apr 20 22:46:37 witherspoon ipmid[921]: Host Time read:[Thu Apr 20 22:35:01 2017 GMT] :: [1492727701]
Apr 20 22:46:37 witherspoon ipmid[921]: Handling Set-SEL-Time:[0xA], Cmd:[0x49]
Apr 20 22:46:37 witherspoon ipmid[921]: Data: 0x5927481B]
Apr 20 22:46:37 witherspoon timemanager[945]: Request to get HOST time
Apr 20 22:46:37 witherspoon timemanager[945]: Thu Apr 20 22:46:37 2017 GMT
Apr 20 22:46:37 witherspoon timemanager[945]:  Host_time_str: [ Thu Apr 20 22:46:37 2017 GMT ] host_time usec: [ 1492728397140698 ] host_offset: [ 0 ]
Apr 20 22:46:37 witherspoon ipmid[921]: Error [Permission denied] setting time
Apr 20 22:53:24 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:53:24] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2418 4.627220
Apr 20 22:53:31 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:53:31] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2414 6.373151
Apr 20 22:53:45 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:53:45] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2368 14.500913
Apr 20 22:54:06 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:54:06] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2376 20.781332
Apr 20 22:54:32 witherspoon phosphor-gevent[859]: Traceback (most recent call last):
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return route.call(**args)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 618, in __call__
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 675, in wrap
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 853, in __call__
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 827, in wrap
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return self.to_jsonp(callback(*a, **kw))
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 1734, in wrapper
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     rv = callback(*a, **ka)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 792, in wrap
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     data = callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 726, in wrap
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 757, in wrap
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 103, in __call__
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return getattr(self, 'do_' + request.method.lower())(**kw)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 238, in do_post
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     return request.route_data['method'](*request.parameter_list)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     **keywords)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Apr 20 22:54:32 witherspoon phosphor-gevent[859]:     message, timeout)
Apr 20 22:54:32 witherspoon phosphor-gevent[859]: DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Apr 20 22:54:32 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:54:32] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 500 2728 25.627742
Apr 20 22:55:43 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:55:43] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2418 6.342227
Apr 20 22:55:59 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:55:59] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2414 15.348397
Apr 20 22:56:21 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:56:21] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2368 21.775982
Apr 20 22:56:46 witherspoon phosphor-gevent[859]: Traceback (most recent call last):
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return route.call(**args)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 618, in __call__
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 675, in wrap
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 853, in __call__
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 827, in wrap
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return self.to_jsonp(callback(*a, **kw))
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 1734, in wrapper
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     rv = callback(*a, **ka)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 792, in wrap
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     data = callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 726, in wrap
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 757, in wrap
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 103, in __call__
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return getattr(self, 'do_' + request.method.lower())(**kw)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 238, in do_post
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     return request.route_data['method'](*request.parameter_list)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     **keywords)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Apr 20 22:56:46 witherspoon phosphor-gevent[859]:     message, timeout)
Apr 20 22:56:46 witherspoon phosphor-gevent[859]: DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Apr 20 22:56:47 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:56:47] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 500 2728 25.813381
Apr 20 22:58:13 witherspoon timemanager[945]: Request to SET Host time
Apr 20 22:58:13 witherspoon timemanager[945]: Curr_Mode: NTPCurr_Owner: BMChost_offset: 0
Apr 20 22:58:13 witherspoon dbus[803]: [system] Rejected send message, 0 matched rules; type="error", sender=":1.72" (uid=0 pid=945 comm="/usr/sbin/timemanager ") interface="(unset)" member="(unset)" error name="org.freedesktop.DBus.Error.Failed" requested_reply="0" destination=":1.67" (uid=0 pid=921 comm="/usr/sbin/ipmid ")
Apr 20 22:58:13 witherspoon ipmid[921]: IPMI HandlinERROR:[0xFF] handling NetFn:[0xA], Cmd:[0x49]
Apr 20 22:58:13 witherspoon timemanager[945]: Request to get HOST time
Apr 20 22:58:13 witherspoon timemanager[945]: Thu Apr 20 22:58:13 2017 GMT
Apr 20 22:58:13 witherspoon timemanager[945]:  Host_time_str: [ Thu Apr 20 22:58:13 2017 GMT ] host_time usec: [ 1492729093127719 ] host_offset: [ 0 ]
Apr 20 22:58:43 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:58:43] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2418 5.236501
Apr 20 22:58:55 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:58:55] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2421 12.209416
Apr 20 22:59:13 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:59:13] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2379 18.156011
Apr 20 22:59:38 witherspoon phosphor-gevent[859]: ::6089:c076:8e91:f402%1342810908 - - [2017-04-20 22:59:38] "POST //xyz/openbmc_project/occ/pass_through/occ0/action/Send HTTP/1.1" 200 2376 24.520624
Apr 20 23:00:04 witherspoon phosphor-gevent[859]: Traceback (most recent call last):
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:     return route.call(**args)
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 618, in __call__
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 675, in wrap
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:     return callback(*a, **kw)
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 853, in __call__
Apr 20 23:00:04 witherspoon phosphor-gevent[859]:     return self.callback(*a, **kw)
Apr 20 23:00:04 witherspoon phosphor-gevent[859```

I noticed two things:
1. the OCC PassThrough application doesn't crash, and when I resend the same command again it works fine, and it sends proper response.
2. This error goes away when I insert delay (one second was enough) between receiving and processing the occ pass through, and sending a new command.

for reference, here is the occ pass through command that suffered a timeout:
```
    sensor_info_resp = session.post(url + '/xyz/openbmc_project/occ/pass_through/occ0/action/Send',
                                    json={'data': [[65, 0, 6, 60, 0, 37, 0, 85, 0]]},
                                    verify=False)```

I send the command in a loop that varies the json data field:
```
import time
sensor_list =[]
start_sensor = 0

while start_sensor < number_of_sensors :
    sensor_info_resp = session.post(url + '/xyz/openbmc_project/occ/pass_through/occ0/action/Send',
                                    json={'data': [[65, 0, 6, 60, 0, 37, start_sensor/256, start_sensor%256, 0]]},
                                    verify=False)
    packet_length = sensor_info_resp.json()['data'][3]*256+sensor_info_resp.json()['data'][4]
    strings = bytearray(sensor_info_resp.json()['data'][5:packet_length+4])
    names = str(strings).split('\x00')    
    sensor_list.extend(names)
    print start_sensor
    start_sensor = start_sensor + len(names)
    time.sleep(1)  # If I remove this 1 second delay, this code suffers the timeout issue reported here.
```

**Comment by geissonator** [comment]
Everything should be good in latest code.
