### ISSUE TITLE
Witherspoon: Jenkins Code update fails 

### ISSUE THREAD

**Issue by yadlapati** [openbmc/openbmc#1946]
Seeing code update fails on systems running GHE code levels.

Update using force code update link works

Output from the run:
```
19:50:03 Started by user Miranda Pacheco
19:50:03 [EnvInject] - Loading node environment variables.
19:50:03 Building remotely on tulpok01p4-ppc64le (docker ppc64le-docker) in workspace /tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update
19:50:03 Set build name.
19:50:03 New build name is '#334-w84'
19:50:03 Next nodes: []
19:50:03 [code-update] $ /bin/bash -xe /tmp/hudson1190326328239947082.sh
19:50:03 + set -uo pipefail
19:50:03 + DOCKER_IMG_NAME=openbmc/ubuntu-obmc-code-update
19:50:03 + WORKSPACE=/tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update
19:50:03 + mkdir -p /tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update
19:50:03 + cd /tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update
19:50:03 + rm -Rf ./openbmc-build-scripts
19:50:03 + rm -Rf ./openbmc-test-automation
19:50:03 + git clone https://gerrit.openbmc-project.xyz/openbmc/openbmc-build-scripts
19:50:03 Cloning into 'openbmc-build-scripts'...
19:50:05 + cd openbmc-build-scripts
19:50:05 + . ./scripts/build-qemu-robot-docker.sh
19:50:05 ++ set -uo pipefail
19:50:05 ++ DOCKER_IMG_NAME=openbmc/ubuntu-robot-qemu
19:50:05 +++ uname -m
19:50:05 ++ '[' ppc64le == ppc64le ']'
19:50:05 ++ DOCKER_BASE=ppc64le/
19:50:05 +++ cat
19:50:05 ++ Dockerfile='FROM ppc64le/ubuntu:latest
19:50:05 
19:50:05 ENV DEBIAN_FRONTEND noninteractive
19:50:05 
19:50:05 RUN apt-get update && apt-get install -yy     debianutils     gawk     git     python     python-dev     python-setuptools     python3     python3-dev     python3-setuptools     socat     texinfo     wget     gcc     libffi-dev     libssl-dev     xterm     mwm     ssh     vim     iputils-ping     sudo     cpio     unzip     diffstat     expect     curl     build-essential
19:50:05 
19:50:05 RUN easy_install     tox     pip     requests
19:50:05 
19:50:05 RUN pip install     json2yaml     robotframework     robotframework-requests     robotframework-sshlibrary     robotframework-scplibrary
19:50:05 
19:50:05 RUN wget https://sourceforge.net/projects/ipmitool/files/ipmitool/1.8.18/ipmitool-1.8.18.tar.bz2
19:50:05 RUN tar xvfj ipmitool-*.tar.bz2
19:50:05 RUN ./ipmitool-1.8.18/configure
19:50:05 RUN make
19:50:05 RUN make install
19:50:05 
19:50:05 RUN grep -q 116 /etc/group || groupadd -g 116 fspcibld
19:50:05 RUN grep -q 57457 /etc/passwd || useradd -d /home/fspcibld -m -u 57457 -g 116                     fspcibld
19:50:05 USER fspcibld
19:50:05 ENV HOME /home/fspcibld
19:50:05 RUN /bin/bash'
19:50:05 ++ docker build -t openbmc/ubuntu-robot-qemu -
19:50:05 Sending build context to Docker daemon 3.072 kB

19:50:05 Step 1 : FROM ppc64le/ubuntu:latest
19:50:05  ---> d2e29d5dd835
19:50:05 Step 2 : ENV DEBIAN_FRONTEND noninteractive
19:50:05  ---> Using cache
19:50:05  ---> 45bb72dc486a
19:50:05 Step 3 : RUN apt-get update && apt-get install -yy     debianutils     gawk     git     python     python-dev     python-setuptools     python3     python3-dev     python3-setuptools     socat     texinfo     wget     gcc     libffi-dev     libssl-dev     xterm     mwm     ssh     vim     iputils-ping     sudo     cpio     unzip     diffstat     expect     curl     build-essential
19:50:05  ---> Using cache
19:50:05  ---> c4d3d4ad4cca
19:50:05 Step 4 : RUN easy_install     tox     pip     requests
19:50:05  ---> Using cache
19:50:05  ---> 2938b5ace4d7
19:50:05 Step 5 : RUN pip install     json2yaml     robotframework     robotframework-requests     robotframework-sshlibrary     robotframework-scplibrary
19:50:05  ---> Using cache
19:50:05  ---> 19aa2845f3b1
19:50:05 Step 6 : RUN wget https://sourceforge.net/projects/ipmitool/files/ipmitool/1.8.18/ipmitool-1.8.18.tar.bz2
19:50:05  ---> Using cache
19:50:05  ---> c99180012c23
19:50:05 Step 7 : RUN tar xvfj ipmitool-*.tar.bz2
19:50:05  ---> Using cache
19:50:05  ---> 8963f94862c8
19:50:05 Step 8 : RUN ./ipmitool-1.8.18/configure
19:50:05  ---> Using cache
19:50:05  ---> d4808225b7cd
19:50:05 Step 9 : RUN make
19:50:05  ---> Using cache
19:50:05  ---> c3db224fd45b
19:50:05 Step 10 : RUN make install
19:50:05  ---> Using cache
19:50:05  ---> ae32a51f8a08
19:50:05 Step 11 : RUN grep -q 116 /etc/group || groupadd -g 116 fspcibld
19:50:05  ---> Using cache
19:50:05  ---> cae4a1a94ac2
19:50:05 Step 12 : RUN grep -q 57457 /etc/passwd || useradd -d /home/fspcibld -m -u 57457 -g 116                     fspcibld
19:50:05  ---> Using cache
19:50:05  ---> a03b5d028995
19:50:05 Step 13 : USER fspcibld
19:50:05  ---> Using cache
19:50:05  ---> 3fc4089f5107
19:50:05 Step 14 : ENV HOME /home/fspcibld
19:50:05  ---> Using cache
19:50:05  ---> 3cec9cc90e2c
19:50:05 Step 15 : RUN /bin/bash
19:50:05  ---> Using cache
19:50:05  ---> 79533102c829
19:50:05 Successfully built 79533102c829
19:50:05 + cd /tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update
19:50:05 + git clone https://github.com/openbmc/openbmc-test-automation.git
19:50:05 Cloning into 'openbmc-test-automation'...
19:50:08 + SHORT_BMC_IMG_NAME=witherspoon-20170628212538.all.tar
19:50:08 + '[' '!' -f ./witherspoon-20170628212538.all.tar ']'
19:50:08 + echo 'Already have downloaded witherspoon-20170628212538.all.tar'
19:50:08 Already have downloaded witherspoon-20170628212538.all.tar
19:50:08 + BMC_IP=w84
19:50:08 + DEFAULT_UPDATE=0
19:50:08 + docker run --user root --env HOME=/home/fspcibld --workdir /home/fspcibld --volume /tmp/fr58p01-slave/workspace/OpenBMC/automated-test/helper-jobs/code-update:/home/fspcibld --tty openbmc/ubuntu-robot-qemu python -m robot -v OPENBMC_HOST:w84 -v FILE_PATH:/home/fspcibld/witherspoon-20170628212538.all.tar -v FORCE_UPDATE:0 --include Initiate_Code_Update_BMC /home/fspcibld/openbmc-test-automation/extended/code_update/update_bmc.robot
19:50:10 ==============================================================================
19:50:10 Update Bmc :: Trigger code update to a target BMC.                            
19:50:10 ==============================================================================
19:50:10 Initiate Code Update BMC :: Initiate a code update on the BMC.        
19:50:12 Boot Count: 0
19:50:12 
19:50:12 Boot Time: 1496775961
19:50:14 URI:https://w84/xyz/openbmc_project/state/host0//attr/RequestedHostTransition, method:Put, args:{u'data': {u'data': 'xyz.openbmc_project.State.Host.Transition.Off'}, u'headers': {u'Content-Type': u'application/json'}}
19:50:14 Response code:200, Content:{
19:50:14   "data": null, 
19:50:14   "message": "200 OK", 
19:50:14   "status": "ok"
19:50:14 }
19:50:16 URI:https://w84/org/openbmc/settings/host0/attr/power_policy, method:Put, args:{u'data': {u'data': u'RESTORE_LAST_STATE'}, u'headers': {u'Content-Type': u'application/json'}}
19:50:17 Response code:200, Content:{
19:50:17   "data": null, 
19:50:17   "message": "200 OK", 
19:50:17   "status": "ok"
19:50:17 }
19:50:31 
                                                                              
[ [33mWARN[0m ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x3fff8981c990>: Failed to establish a new connection: [Errno 111] Connection refused',)': /login
19:50:31 Initiate Code Update BMC :: Initiate a code update on the BMC.        
                                                                              
[ [33mWARN[0m ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x3fff8981cad0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /login
19:50:31 Initiate Code Update BMC :: Initiate a code update on the BMC.        
                                                                              
[ [33mWARN[0m ] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x3fff8981cc50>: Failed to establish a new connection: [Errno 111] Connection refused',)': /login
19:50:31 Initiate Code Update BMC :: Initiate a code update on the BMC.        
                                                                              
[ [33mWARN[0m ] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x3fff89881a90>, 'Connection to w84 timed out. (connect timeout=20.0)')': /login
19:51:11 Initiate Code Update BMC :: Initiate a code update on the BMC.        
                                                                              
[ [33mWARN[0m ] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x3fff89881290>, 'Connection to w84 timed out. (connect timeout=20.0)')': /login
19:51:32 Initiate Code Update BMC :: Initiate a code update on the BMC.        
19:52:49 Boot Count: 0
19:52:49 
19:52:49 Boot Time: 1496775961
19:52:49 [32m.[0mURI:https://w84/org/openbmc/control/flash/bmc/attr/preserve_network_settings, method:Put, args:{u'data': {u'data': 1}, u'headers': {u'Content-Type': u'application/json'}}
19:52:50 Response code:200, Content:{
19:52:50   "data": null, 
19:52:50   "message": "200 OK", 
19:52:50   "status": "ok"
19:52:50 }
19:52:50 [32m.[0m[32m.'Unpack Error' does not contain 'to apply'
19:52:52 [0m[31mF[0mstatus_ping:                                      None
19:52:55 #(UTC) 2017/07/10 19:52:55.472295 -  165.731627 - Collecting FFDC.
19:52:55 #(UTC) 2017/07/10 19:52:55.480316 -    0.008021 - Issuing: Get Test Dir and Name
19:52:55 ffdc_dir_path:                                    /home/fspcibld/logs/20170710195255473883_UpdateBmc/20170710195255473883_InitiateCodeUpdateBMC/
19:52:55 ffdc_prefix:                                      20170710195255473883_
19:52:55 #(UTC) 2017/07/10 19:52:55.513074 -    0.032758 - Issuing: Create Directory  /home/fspcibld/logs/20170710195255473883_UpdateBmc/20170710195255473883_InitiateCodeUpdateBMC/
19:53:09 #(UTC) 2017/07/10 19:53:09.969087 -   14.456013 - Finished collecting FFDC.
19:53:09 TEST_HISTORY:                                     /home/fspcibld/logs//test_history.txt
19:53:09 [32m.[0m
                                                                              
Initiate Code Update BMC :: Initiate a code update on the BMC.        | [31mFAIL[0m |
19:53:09 'Unpack Error' does not contain 'to apply'
19:53:09 ------------------------------------------------------------------------------
19:53:09 Update Bmc :: Trigger code update to a target BMC.                    | [31mFAIL[0m |
19:53:09 1 critical test, 0 passed, 1 failed
19:53:09 1 test total, 0 passed, 1 failed
19:53:09 ==============================================================================
19:53:09 Output:  /home/fspcibld/output.xml
19:53:10 Log:     /home/fspcibld/log.html
19:53:10 Report:  /home/fspcibld/report.html
19:53:10 Build step 'Execute shell' marked build as failure
19:53:10 Set build name.
19:53:10 New build name is '#334-w84'
19:53:10 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#334-w84', new value: '#334-w84'
19:53:11 [PostBuildScript] - Execution post build scripts.
19:53:11 [code-update] $ /bin/bash -xe /tmp/hudson2146762907998730904.sh
19:53:11 + curl -s http://tulpok01p4.aus.stglabs.ibm.com:8080/jenkins/job/OpenBMC/job/automated-test/job/helper-jobs/job/code-update/334//consoleText
19:53:11 Robot results publisher started...
19:53:11 -Parsing output xml:
19:53:11 Done!
19:53:11 -Copying log files to build dir:
19:53:11 Done!
19:53:11 -Assigning results to build:
19:53:11 Done!
19:53:11 -Checking thresholds:
19:53:11 Done!
19:53:11 Done publishing Robot results.
19:53:11 Collecting metadata...
19:53:11 Metadata collection done.
19:53:11 Finished: FAILURE
```

**Comment by geissonator** [comment]
We're having REST login issues again after the prepareForUpdate reboot.  And then it started working for FFDC collection on the failure :(
```
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: Traceback (most recent call last):
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     result = self._run(*self.args, **self.kwargs)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 102, in wrap_socket_and_handle
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 404, in wrap_socket
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     ciphers=ciphers)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 113, in __init__
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     self.do_handshake()
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 324, in do_handshake
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     return self._sslobj.do_handshake()
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: <Greenlet at 0x7658b2b0: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x765677d0 fileno=5 address=('::2cc2:8047:b04d:af76%1991200160', 443, 0, 1991200160)>>(<socket at 0x7643c210 fileno=9>, ('::6059:ad76:8e91:f402%1199549204', 49184, 0, 119)> failed with SSLEOFError
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: Traceback (most recent call last):
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     result = self._run(*self.args, **self.kwargs)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/server.py", line 102, in wrap_socket_and_handle
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 404, in wrap_socket
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     ciphers=ciphers)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 113, in __init__
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     self.do_handshake()
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:   File "/usr/lib/python2.7/site-packages/gevent/ssl.py", line 324, in do_handshake
Jul 10 13:05:40 witherspoon phosphor-gevent[891]:     return self._sslobj.do_handshake()
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
Jul 10 13:05:40 witherspoon phosphor-gevent[891]: <Greenlet at 0x7658b580: <bound method WSGIServer.wrap_socket_and_handle of <WSGIServer at 0x765677d0 fileno=5 address=('::2cc2:8047:b04d:af76%1991200160', 443, 0, 1991200160)>>(<socket at 0x7643c1b0 fileno=10>, ('::6059:ad76:8e91:f402%1199549204', 49186, 0, 119)> failed with SSLEOFError


Jul 10 13:05:55 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:55] "POST /login HTTP/1.1" 200 320 0.048444
Jul 10 13:05:55 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57666).
Jul 10 13:05:55 witherspoon dropbear[994]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:05:55 witherspoon dropbear[994]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:05:55 witherspoon dropbear[994]: Child connection from ::ffff:9.41.165.103:57666
Jul 10 13:05:56 witherspoon dropbear[994]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57666
Jul 10 13:05:56 witherspoon dropbear[995]: lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
Jul 10 13:05:56 witherspoon dropbear[995]: lastlog_openseek: /var/log/lastlog is not a file or directory!
Jul 10 13:05:57 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57668).
Jul 10 13:05:57 witherspoon dropbear[999]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:05:57 witherspoon dropbear[999]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:05:57 witherspoon dropbear[999]: Child connection from ::ffff:9.41.165.103:57668
Jul 10 13:05:58 witherspoon dropbear[999]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57668
Jul 10 13:05:58 witherspoon dropbear[1000]: lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
Jul 10 13:05:58 witherspoon dropbear[1000]: lastlog_openseek: /var/log/lastlog is not a file or directory!
Jul 10 13:05:59 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:59] "POST /login HTTP/1.1" 200 320 0.033287
Jul 10 13:05:59 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:59] "GET /xyz/openbmc_project/state/BMC0/ HTTP/1.1" 404 308 0.030837
Jul 10 13:05:59 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:59] "POST /login HTTP/1.1" 200 320 0.035808
Jul 10 13:05:59 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:59] "GET /xyz/openbmc_project/state/bmc0//attr/CurrentBMCState HTTP/1.1" 200 212 0.062129
Jul 10 13:05:59 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:05:59] "POST /login HTTP/1.1" 200 320 0.037175
Jul 10 13:06:00 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:00] "PUT /org/openbmc/control/flash/bmc/attr/preserve_network_settings HTTP/1.1" 200 169 0.233495
Jul 10 13:06:00 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:00] "POST /login HTTP/1.1" 200 320 0.033278
Jul 10 13:06:00 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:00] "GET /org/openbmc/control/flash/bmc HTTP/1.1" 200 380 0.086234
Jul 10 13:06:00 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57678).
Jul 10 13:06:00 witherspoon dropbear[1006]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:06:00 witherspoon dropbear[1006]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:06:00 witherspoon dropbear[1006]: Child connection from ::ffff:9.41.165.103:57678
Jul 10 13:06:01 witherspoon dropbear[1006]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57678
Jul 10 13:06:01 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:01] "POST /login HTTP/1.1" 200 320 0.033183
Jul 10 13:06:01 witherspoon bmc_update.py[920]: Download complete. Updating...
Jul 10 13:06:01 witherspoon bmc_update.py[920]: file could not be opened successfully
Jul 10 13:06:01 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:01] "POST /org/openbmc/control/flash/bmc/action/update HTTP/1.1" 200 169 0.403178
Jul 10 13:06:02 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:02] "POST /login HTTP/1.1" 200 320 0.033445
Jul 10 13:06:02 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:02] "GET /org/openbmc/control/flash/bmc HTTP/1.1" 200 401 0.078824
Jul 10 13:06:02 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:02] "POST /login HTTP/1.1" 200 320 0.033346
Jul 10 13:06:02 witherspoon phosphor-gevent[891]: ::6059:ad76:8e91:f402%1199549204 - - [2017-07-10 13:06:02] "GET /xyz/openbmc_project/state/host0//attr/CurrentHostState HTTP/1.1" 200 212 0.049117
Jul 10 13:06:05 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57686).
Jul 10 13:06:05 witherspoon dropbear[1008]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:06:05 witherspoon dropbear[1008]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:06:05 witherspoon dropbear[1008]: Child connection from ::ffff:9.41.165.103:57686
Jul 10 13:06:06 witherspoon dropbear[1008]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57686
Jul 10 13:06:06 witherspoon dropbear[1009]: lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
Jul 10 13:06:06 witherspoon dropbear[1009]: lastlog_openseek: /var/log/lastlog is not a file or directory!
Jul 10 13:06:07 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57688).
Jul 10 13:06:07 witherspoon dropbear[1015]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:06:07 witherspoon dropbear[1015]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:06:07 witherspoon dropbear[1015]: Child connection from ::ffff:9.41.165.103:57688
Jul 10 13:06:07 witherspoon dropbear[1015]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57688
Jul 10 13:06:07 witherspoon dropbear[1016]: lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
Jul 10 13:06:07 witherspoon dropbear[1016]: lastlog_openseek: /var/log/lastlog is not a file or directory!
Jul 10 13:06:10 witherspoon systemd[1]: Started SSH Per-Connection Server (9.41.165.103:57690).
Jul 10 13:06:10 witherspoon dropbear[1025]: Failed loading /etc/dropbear/dropbear_dss_host_key
Jul 10 13:06:10 witherspoon dropbear[1025]: Failed loading /etc/dropbear/dropbear_ecdsa_host_key
Jul 10 13:06:10 witherspoon dropbear[1025]: Child connection from ::ffff:9.41.165.103:57690
Jul 10 13:06:11 witherspoon dropbear[1025]: PAM password auth succeeded for 'root' from ::ffff:9.41.165.103:57690
Jul 10 13:06:11 witherspoon dropbear[1026]: lastlog_perform_login: Couldn't stat /var/log/lastlog: No such file or directory
Jul 10 13:06:11 witherspoon dropbear[1026]: lastlog_openseek: /var/log/lastlog is not a file or directory!
```

**Comment by gkeishin** [comment]
This is SCP timedout issue where the network dropped and the tar image is not copied and it tried to update with invalid image 
```
19:53:09 'Unpack Error' does not contain 'to apply'
```

**Comment by geissonator** [comment]
@gkeishin has kindly posted a workaround in the automated test framework for now - https://gerrit.openbmc-project.xyz/#/c/5212/

This all changes once the official code update process gets in place from @anoo1 and team so don't want to spend much time debugging the scp partial copy issue (I assume some sort of network problem).
