### ISSUE TITLE
The name xyz.openbmc_project.Hwmon-524131999.Hwmon1 was not provided by any .service files

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2723]
This looks like something new in master.  Not clear yet if it's impacting anything, but I'm having issues getting code update to work on witherspoon

```
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]: Traceback (most recent call last):
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 862, in _handle
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return route.call(**args)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 931, in __call__
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return self.callback(*a, **kw)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 988, in wrap
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return callback(*a, **kw)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 1171, in __call__
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return self.callback(*a, **kw)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 1145, in wrap
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return self.to_jsonp(callback(*a, **kw))
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/bottle.py", line 1734, in wrapper
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     rv = callback(*a, **ka)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 1110, in wrap
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     data = callback(*a, **kw)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 209, in __call__
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     return getattr(self, 'do_' + request.method.lower())(**kw)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/wsgi/apps/rest_dbus.py", line 315, in do_get
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     mapper_data=request.route_data['map']).dataitems()}
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/bindings.py", line 167, in enumerate_subtree
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     obj = self.bus.get_object(owner, path, introspect=False)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     follow_name_owner_changes=follow_name_owner_changes)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     self._named_service = conn.activate_name_owner(bus_name)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     self.start_service_by_name(bus_name)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     'su', (bus_name, flags)))
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]:     message, timeout)
Dec 15 20:17:13 witherspoon phosphor-gevent[1201]: DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name xyz.openbmc_project.Hwmon-524131999.Hwmon1 was not provided by any .service files
```

```
[witherspoon]# cat /etc/os-release 
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v2.0-137"
VERSION_ID="v2.0-137-g4f1dc5a"
PRETTY_NAME="Ph
```

**Comment by geissonator** [comment]
Haven't seen this one in a while.
