### ISSUE TITLE
phosphor-mapper[1851]: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#2796]
Noticed this in a mapper bump test on real hardware.

```
Jan 16 15:48:45 witherspoon kernel[1023]: [  411.040000] systemd[1]: mapper-wait@-xyz-openbmc_project-control-host0-restriction_mode.service: Unit entered failed state.
Jan 16 15:44:45 witherspoon systemd[1]: Stopped Phosphor Host State Manager.
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]: Traceback (most recent call last):
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]:   File "/usr/sbin/phosphor-mapper", line 20, in <module>
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]:     import obmc.mapper.server
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 544
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]:     svc_map = def svc: (
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]:                 ^
Jan 16 15:53:40 witherspoon phosphor-mapper[1851]: SyntaxError: invalid syntax
Jan 16 15:48:45 witherspoon kernel[1023]: [  411.070000] systemd[1]: mapper-wait@-xyz-openbmc_project-control-host0-restriction_mode.service: Failed with result 'exit-code'.
```

I assume related to our fixes for pep8 in https://github.com/openbmc/phosphor-objmgr/commit/a1f24229e0c879ea12782784737c3359676a40e1

**Comment by rfrandse** [comment]
<https://gerrit.openbmc-project.xyz/8504> Ignore E731 in objmgr
Fixes  #2796 phosphor-mapper[1851]: SyntaxError: invalid syntax
