### ISSUE TITLE
Witherspoon IPMI enable and disable Power supply redundancy

### ISSUE THREAD

**Issue by gkeishin** [openbmc/openbmc#2992]
```
/xyz/openbmc_project/sensors/chassis/enumerate
{
    "/xyz/openbmc_project/sensors/chassis/PowerSupplyRedundancy": {
        "error": 0,
        "units": "",
        "value": "Enabled"
    }
}
```

`To disable`
```
-bash-4.1$ ipmitool -I lanplus -C 3 -P 0penBmc -H xx.xx.xx.xx raw 0x04 0x2d 0x0b
Unable to send RAW command (channel=0x0 netfn=0x4 lun=0x0 cmd=0x2d rsp=0xcb): Requested sensor, data, or record not found
-bash-4.1$
```
and same with enable too.

```
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v2.1-240"
VERSION_ID="v2.1-240-gc244f65"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v2.1-240"
BUILD_ID="v2.1"
root@witherspoon:~#
```

`Journald Snippet`
```
Mar 09 13:07:24 witherspoon systemd[1]: Started Network IPMI daemon.
Mar 09 13:07:24 witherspoon kernel: nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
Mar 09 13:07:24 witherspoon kernel[941]: [ 3716.459087] nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering handler: /usr/lib/net-ipmid/libapphandler.so.0
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x36]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1836
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0xFF]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command18ff
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x22]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1822
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x24]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1824
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1825
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x1]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1801
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x4]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1804
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x8]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1808
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x6]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1806
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x40]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1840
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x41]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1841
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x42]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1842
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x37]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1837
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x4], Cmd:[0xFF]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command10ff
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x4], Cmd:[0x2F]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command102f
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x4], Cmd:[0x30]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1030
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x4], Cmd:[0x2D]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command102d
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1022
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1020
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1021
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command1027
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0xFF]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command28ff
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x40]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2840
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x48]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2848
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x49]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2849
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x42]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2842
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x43]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2843
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x46]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2846
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x44]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2844
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x47]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2847
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x10]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2810
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0xA], Cmd:[0x11]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2811
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2820
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2822
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Command2823
Mar 09 13:07:25 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0xFF]
Mar 09 13:07:25 witherspoon netipmid[1372]: I> Registering Commandff
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0x0]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command0
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0x9]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command9
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0x1]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0x2]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command2
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x0], Cmd:[0x8]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command8
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x3]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb003
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x4]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb004
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x5]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb005
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x6]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb006
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x8]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb008
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x9]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb009
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0xA]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb00a
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb001
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb010
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb002
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb007
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb013
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb012
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0xC], Cmd:[0xFF]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command30ff
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0xC], Cmd:[0x1]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command3001
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0xC], Cmd:[0x2]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command3002
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x2]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1802
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x6], Cmd:[0x3]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1803
Mar 09 13:07:26 witherspoon netipmid[1372]: Registering NetFn:[0x2C], Cmd:[0x0]
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Commandb000
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command100000
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command120000
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command140000
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1838
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command183b
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command183c
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command10000
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1848
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command1849
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command184a
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command3021
Mar 09 13:07:26 witherspoon netipmid[1372]: I> Registering Command3022
Mar 09 13:07:26 witherspoon netipmid[1372]: >> GetChannelCapabilities
Mar 09 13:07:26 witherspoon netipmid[1372]: << GetChannelCapabilities
Mar 09 13:07:26 witherspoon netipmid[1372]: >> GetChannelCapabilities
Mar 09 13:07:26 witherspoon netipmid[1372]: << GetChannelCapabilities
Mar 09 13:07:26 witherspoon netipmid[1372]: >> openSession
Mar 09 13:07:26 witherspoon netipmid[1372]: << openSession
Mar 09 13:07:26 witherspoon netipmid[1372]: >> RAKP12
Mar 09 13:07:26 witherspoon netipmid[1372]: << RAKP12
Mar 09 13:07:26 witherspoon netipmid[1372]: >> RAKP34
Mar 09 13:07:26 witherspoon netipmid[1372]: << RAKP34
Mar 09 13:07:26 witherspoon netipmid[1372]: >> setSessionPrivilegeLevel
Mar 09 13:07:26 witherspoon netipmid[1372]: << setSessionPrivilegeLevel
Mar 09 13:07:26 witherspoon netipmid[1372]: E> Table:: Command Not found: 0xb03e
Mar 09 13:07:26 witherspoon netipmid[1372]: Failed to create a method call: Invalid request descriptorFailed to find Sensor 0x0b
```

**Comment by gkeishin** [comment]
````
root@witherspoon:~# cat /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="v2.1-239"
VERSION_ID="v2.1-239-g98861c5"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) v2.1-239"
BUILD_ID="v2.1"
root@witherspoon:~#

```
Yeah seen same on latest master too. @dkodihal

**Comment by ngorugan** [comment]
When this issue occurs, busctl monitor giving below given info

```
Type=error  Endian=l  Flags=1  Version=1  Priority=0 Cookie=68  ReplyCookie=29
  Sender=:1.84  Destination=:1.342
  ErrorName=org.freedesktop.DBus.Error.UnknownMethod  ErrorMessage="Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: getObjectFromByteId is not a valid method of interface org.openbmc.managers.System
  };
```


It is not able to find the method "getObjectFromByteId" on the interface  "org.openbmc.managers.System"

```
root@witherspoon:/tmp#  busctl introspect org.openbmc.managers.System /org/openbmc/managers/System  |cat  | grep getObjectFromByteId
root@witherspoon:/tmp#
```

But with master build I am not seeing this issue.

```
root@witherspoon:~# busctl introspect org.openbmc.managers.System /org/openbmc/managers/System  |cat  | grep getObjectFromByteId
.getObjectFromByteId                method    sy         (ss) 

root@witherspoon:~# cat  /etc/os-release
ID="openbmc-phosphor"
NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)"
VERSION="ibm-v2.1"
VERSION_ID="ibm-v2.1-105-g4397421-r1-0-gbeb0b18"
PRETTY_NAME="Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) ibm-v2.1"
BUILD_ID="ibm-v2.1-105-g4397421-r1"
```

Still debugging.

**Comment by gkeishin** [comment]
Thanks @ngorugan  keep posted.

**Comment by ngorugan** [comment]
@gkeishin  It seems this issue is dup of issues #2975.

**Comment by gkeishin** [comment]
Yup.. looks like that only.. @geissonator fix should cover this one. I just ran it on his patch and it worked. So we can close this one.
