### ISSUE TITLE
Mapper get "org.openbmc.control.Flasher discovery failure" on BMC boot

### ISSUE THREAD

**Issue by mine260309** [openbmc/openbmc#3087]
On latest OpenBMC (e.g. 438ce124e4a14e843690cb11ba8aa0b345cab1fb), mapper gets below errors during boot.
The issue occurs on both P9 Romulus and P8 Palmetto, so it should be a common issue for systems without UBI-FS feature.

It does not seem to cause any side effect, but it's better to clean it up.

```
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: flasher: , BMC = 1, address = 0x0
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: Setting up flash
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: Starting flasher: bios,,/org/openbmc/control/flash/bios,
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: flasher: , BMC = 1, address = 0x0
Apr 11 14:43:28 rom285 flash_bios.exe[1029]: Setting up flash
Apr 11 14:43:28 rom285 phosphor-mapper[965]: org.openbmc.control.Flasher discovery failure on / - retry
Apr 11 14:43:28 rom285 phosphor-mapper[965]: org.openbmc.control.Flasher discovery failure on /
Apr 11 14:43:29 rom285 phosphor-mapper[965]: Traceback (most recent call last):
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 72, in __call__
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     self._find_interfaces(path)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 171, in _find_interfaces
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     obj = conn.get_object(service, path, introspect=False)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     follow_name_owner_changes=follow_name_owner_changes)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in __init__
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     self._named_service = conn.activate_name_owner(bus_name)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     self.start_service_by_name(bus_name)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     'su', (bus_name, flags)))
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     message, timeout)
Apr 11 14:43:29 rom285 phosphor-mapper[965]: DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.openbmc.control.Flasher was not provided by any .service files
Apr 11 14:43:29 rom285 phosphor-mapper[965]: ERROR:dbus.connection:Exception in handler for D-Bus signal:
Apr 11 14:43:29 rom285 phosphor-mapper[965]: Traceback (most recent call last):
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     self._handler(*args, **kwargs)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 405, in bus_handler
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     self.process_new_owner(owned_name, new)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 383, in process_new_owner
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     return self.discover([(owned_name, owner)])
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 510, in discover
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     iface_match=self.interface_match)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 178, in find_dbus_interfaces
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     return _FindInterfaces()(path)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 74, in __call__
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     error_callback(service, path, e)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 485, in discovery_error_retry
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     iface_match=self.interface_match)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 178, in find_dbus_interfaces
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     return _FindInterfaces()(path)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 74, in __call__
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     error_callback(service, path, e)
Apr 11 14:43:29 rom285 phosphor-mapper[965]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 291, in discovery_error
Apr 11 14:43:29 rom285 phosphor-mapper[965]:     del self.bus_map[owner]
Apr 11 14:43:29 rom285 phosphor-mapper[965]: KeyError: dbus.String(u'org.openbmc.control.Flasher')
```

**Comment by mine260309** [comment]
The issue occurs when `on_init()` is called (e.g. `obmc-flash-init.service` is started), and `flash_bios.exe` will fork `flasher.exe`, which run and exits quickly.

During `flasher.exe` running, `phosphor-mapper` will try to discover `org.openbmc.control.Flasher` interface and because it exits quickly, mapper fails to discovery and prints the error.

This issue really does not matter.

**Comment by mine260309** [comment]
Tried to add `org.openbmc.control.Flasher` into interface_blacklist of mapper, but the error log still prints, because the match is called after that.

**Comment by mine260309** [comment]
Still a problem.
The legacy services will be removed in future, then this issue could be closed.
