### ISSUE TITLE
xyz.openbmc_project.Events discovery failure

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#3173]
Not sure what's causing this but we're seeing it consistently on our witherspoon system with latest master code.

```
May 10 15:19:47 w54 phosphor-mapper[1011]: ObjectMapper startup complete.  Discovery in progress...
May 10 15:20:02 w54 phosphor-mapper[1011]: ObjectMapper discovery complete
May 10 15:20:35 w54 phosphor-mapper[1011]: xyz.openbmc_project.Events discovery failure on / - retry
May 10 15:21:00 w54 phosphor-mapper[1011]: xyz.openbmc_project.Events discovery failure on /
May 10 15:21:00 w54 phosphor-mapper[1011]: DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
May 10 15:21:00 w54 phosphor-mapper[1011]: Traceback (most recent call last):
May 10 15:21:00 w54 phosphor-mapper[1011]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 607, in msg_reply_handler
May 10 15:21:00 w54 phosphor-mapper[1011]:     *message.get_args_list()))
May 10 15:21:00 w54 phosphor-mapper[1011]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 176, in <lambda>
May 10 15:21:00 w54 phosphor-mapper[1011]:     error_handler=lambda x: error_callback(service, path, x))
May 10 15:21:00 w54 phosphor-mapper[1011]:   File "/usr/lib/python2.7/site-packages/obmc/mapper/server.py", line 291, in discovery_error
May 10 15:21:00 w54 phosphor-mapper[1011]:     del self.bus_map[owner]
May 10 15:21:00 w54 phosphor-mapper[1011]: KeyError: dbus.String(u'xyz.openbmc_project.Events')
```

```
# systemctl status phosphor-dbus-monitor | cat
\u25cf phosphor-dbus-monitor.service - Phosphor DBus Monitor
   Loaded: loaded (/lib/systemd/system/phosphor-dbus-monitor.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-05-10 15:20:02 UTC; 4min 49s ago
 Main PID: 1127 (phosphor-dbus-m)
   CGroup: /system.slice/phosphor-dbus-monitor.service
           \u2514\u25001127 phosphor-dbus-monitor

May 10 15:20:02 w54 systemd[1]: Started Phosphor DBus Monitor.
```

```
# busctl tree xyz.openbmc_project.Events | cat
\u2514\u2500/xyz
  \u2514\u2500/xyz/openbmc_project
    \u2514\u2500/xyz/openbmc_project/events
[w54]# 
[w54]# busctl introspect xyz.openbmc_project.Events /xyz/openbmc_project/events| cat
NAME                                TYPE      SIGNATURE  RESULT/VALUE  FLAGS
org.freedesktop.DBus.Introspectable interface -          -             -
.Introspect                         method    -          s             -
org.freedesktop.DBus.ObjectManager  interface -          -             -
.GetManagedObjects                  method    -          a{oa{sa{sv}}} -
.InterfacesAdded                    signal    oa{sa{sv}} -             -
.InterfacesRemoved                  signal    oas        -             -
org.freedesktop.DBus.Peer           interface -          -             -
.GetMachineId                       method    -          s             -
.Ping                               method    -          -             -
org.freedesktop.DBus.Properties     interface -          -             -
.Get                                method    ss         v             -
.GetAll                             method    s          a{sv}         -
.Set                                method    ssv        -             -
.PropertiesChanged                  signal    sa{sv}as   -             -

```

**Comment by amboar** [comment]
I've seen this in my testing of the mapper-perf topic. I was hoping it wasn't something I'd introduced, so thanks for at least confirming that :)
