### ISSUE TITLE
Error building phosphor-webui.bb

### ISSUE THREAD

**Issue by gtmills** [openbmc/openbmc#3200]
```
| [0] Hash: 4c120fd134b8136b9210
| Version: webpack 3.12.0
| Child
|     Hash: 4c120fd134b8136b9210
|     Time: 9620ms
|                                       Asset       Size  Chunks                    Chunk Names
|                       images/favicon.ico.gz  812 bytes          [emitted]
|      af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
|        f4769f9bdb7466be65088239c12046d1.eot    20.1 kB          [emitted]
|      448c34a56d699c29117adc64c43affeb.woff2      18 kB          [emitted]
|       fa2772327f55d8198301fdb8bcfc8158.woff    23.4 kB          [emitted]
|        641dbdb45c26f493147f6015a8b9e7d6.svg  255 bytes          [emitted]
|                 images/icon-check-white.svg  255 bytes          [emitted]
|               images/icon-refresh-white.svg  332 bytes          [emitted]
|                          images/openBMC.png    13.6 kB          [emitted]
|     11c917ac86c399906c00ec892116edae.svg.gz  490 bytes          [emitted]
|     820788679f2a21559e69ba8cd8c6fc5e.svg.gz    1.65 kB          [emitted]
|     33541d53ee6b06b037eea48a7c285bb8.svg.gz  391 bytes          [emitted]
|     d327568f3dec64be664890db40431129.svg.gz  391 bytes          [emitted]
|     d4099f59b94b4f9c6a34c9edf2ec8ad3.svg.gz  312 bytes          [emitted]
|     1c120e1d678099f840bd6f46dc6d88b0.svg.gz  439 bytes          [emitted]
|     08a00c99750c36a29b4c0a9d6bf39b46.svg.gz  370 bytes          [emitted]
|     f60e78cb97c99abd512d2b4074d37d61.svg.gz  438 bytes          [emitted]
|     a65714db6ce091fd338553c580cc3964.svg.gz  381 bytes          [emitted]
|     33ebb9bfcf705db709a9d138305a3a3c.svg.gz  377 bytes          [emitted]
|     8d061c596079e9beb33194850b0d8d4a.svg.gz  322 bytes          [emitted]
|     6ff7a6aefc8825d1b1f593e9536a077d.svg.gz  357 bytes          [emitted]
|     f4c7d5ba924e4268b7589fe8df03f4ae.svg.gz  339 bytes          [emitted]
|     1a6e0b3f7c81a9737afea5a0284e8560.svg.gz  444 bytes          [emitted]
|     02812ad9d3ecd7547217e46386a2d611.svg.gz  440 bytes          [emitted]
|     9f6263b910c2035145cf52e09238f4d4.svg.gz  449 bytes          [emitted]
|     885a82e6116c36aec2ccf929c88ffda6.svg.gz  396 bytes          [emitted]
|     0b0a703d2ec880a794b00b5906458dd0.svg.gz  380 bytes          [emitted]
|                               index.html.gz  446 bytes          [emitted]
|                              favicon.ico.gz  812 bytes          [emitted]
|                        images/crit-x.svg.gz  396 bytes          [emitted]
|               images/icon-arrow-blue.svg.gz  444 bytes          [emitted]
|       fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
|                    images/icon-check.svg.gz  312 bytes          [emitted]
|               images/icon-arrow-gray.svg.gz  440 bytes          [emitted]
|                  images/icon-control.svg.gz  337 bytes          [emitted]
|               images/icon-copy-white.svg.gz  416 bytes          [emitted]
|                   images/icon-config.svg.gz  670 bytes          [emitted]
|                     images/icon-copy.svg.gz  391 bytes          [emitted]
|                 images/icon-critical.svg.gz  438 bytes          [emitted]
|                      images/icon-off.svg.gz  377 bytes          [emitted]
|                   images/icon-health.svg.gz  426 bytes          [emitted]
|                 images/icon-overview.svg.gz  260 bytes          [emitted]
|                       images/icon-on.svg.gz  381 bytes          [emitted]
|                     images/icon-plus.svg.gz  339 bytes          [emitted]
|                    images/icon-power.svg.gz  490 bytes          [emitted]
|                   images/icon-return.svg.gz  322 bytes          [emitted]
|                   images/icon-search.svg.gz  449 bytes          [emitted]
|                  images/icon-standby.svg.gz  357 bytes          [emitted]
|           images/icon-trashcan-white.svg.gz  439 bytes          [emitted]
|                 images/icon-trashcan.svg.gz  391 bytes          [emitted]
|                   images/icon-upload.svg.gz  256 bytes          [emitted]
|                  images/icon-warning.svg.gz  370 bytes          [emitted]
|                          images/logo.svg.gz    1.65 kB          [emitted]
|                    images/warn-slash.svg.gz  380 bytes          [emitted]
|     e18bbf611f2a2e43afc071aa2f4e1512.ttf.gz    23.4 kB          [emitted]
|     89889688147bd7575d6327160d64e760.svg.gz    26.5 kB          [emitted]
|                              css/app.css.gz    30.5ERROR: phosphor-webui-1.0-r0 do_compile: Function failed: do_compile (log file is located at /home/bmcbuild/releases/obmc910/Builds/ob910.1821.20180521c/86add116627980d099ac9a80c14970a754f10c85/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/temp/log.do_compile.6828)
ERROR: Logfile of failure stored in: /home/bmcbuild/releases/obmc910/Builds/ob910.1821.20180521c/86add116627980d099ac9a80c14970a754f10c85/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/temp/log.do_compile.6828
ERROR: Task (/home/bmcbuild/releases/obmc910/Builds/ob910.1821.20180521c/86add116627980d099ac9a80c14970a754f10c85/meta-phosphor/common/recipes-phosphor/webui/phosphor-webui.bb:do_compile) failed with exit code '1'
Build failed
 kB          [emitted]
|                          css/app.css.map.gz    36.7 kB          [emitted]
|     b06871f281fee6b241d60582ae9369b9.ttf.gz    98.1 kB          [emitted]
|     674f50d287a8c48dc19ba404d20fe713.eot.gz    98.2 kB          [emitted]
|     912ec66d7572ff821749319396470bde.svg.gz     134 kB          [emitted]
|              app.4c120fd134b8136b9210.js.gz     861 kB          [emitted]  [big]
|          app.4c120fd134b8136b9210.js.map.gz     956 kB          [emitted]  [big]
|        [8] ./app/index.js 11.8 kB {0} [built]
|             factory:34ms building:808ms = 842ms
|       [27] ./app/constants/index.js 279 bytes {0} [built]
|            [] -> factory:54ms building:39ms = 93ms
|       [28] ./app/constants/environment-constants.js 609 bytes {0} [built]
|            [] -> factory:55ms building:42ms = 97ms
|       [29] ./app/common/services/index.js 320 bytes {0} [built]
|            [] -> factory:72ms building:426ms = 498ms
|       [30] ./app/common/services/constants.js 6.43 kB {0} [built]
|            [] -> factory:73ms building:435ms = 508ms
|       [31] ./app/common/services/dataService.js 4.76 kB {0} [built]
|            [] -> factory:73ms building:455ms = 528ms
|       [32] ./app/common/services/api-utils.js 41.5 kB {0} [built]
|            [] -> factory:73ms building:772ms = 845ms
|       [33] ./app/common/services/userModel.js 2.15 kB {0} [built]
|            [] -> factory:73ms building:464ms = 537ms
|       [34] ./app/common/services/apiInterceptor.js 2.13 kB {0} [built]
|            [] -> factory:74ms building:783ms = 857ms
|       [35] ./app/common/filters/index.js 568 bytes {0} [built]
|            [] -> factory:74ms building:788ms = 862ms
|       [36] ./app/common/directives/index.js 161 bytes {0} [built]
|            [] -> factory:74ms building:789ms = 863ms
|       [37] ./app/common/directives/errors.js 522 bytes {0} [built]
|            [] -> factory:75ms building:791ms = 866ms
|       [39] ./app/common/directives/app-header.js 3.51 kB {0} [built]
|            [] -> factory:76ms building:804ms = 880ms
|       [55] ./app/common/directives/firmware-list.js 1.24 kB {0} [built]
|            [] -> factory:78ms building:868ms = 946ms
|       [66] ./app/server-control/index.js 1.73 kB {0} [built]
|            [] -> factory:57ms building:113ms = 170ms
|         + 118 hidden modules
| 
|     ERROR in app.4c120fd134b8136b9210.js from UglifyJs
|     Invalid assignment [app.4c120fd134b8136b9210.js:58683,47]
|     Child html-webpack-plugin for "index.html":
|          1 asset
|            [0] ./node_modules/html-webpack-plugin/lib/loader.js!./app/index.html 790 bytes {0} [built]
|                 factory:344ms building:533ms = 877ms
|     Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--1-2!node_modules/postcss-loader/lib/index.js!node_modules/bootstrap/dist/css/bootstrap-theme.css:
|            2 modules
|     Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--1-2!node_modules/postcss-loader/lib/index.js!node_modules/font-awesome/css/font-awesome.css:
|                                          Asset     Size  Chunks             Chunk Names
|         af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
|          fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
|          + 3 hidden assets
|            8 modules
|     Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--1-2!node_modules/postcss-loader/lib/index.js!node_modules/bootstrap/dist/css/bootstrap.css:
|                                          Asset     Size  Chunks             Chunk Names
|           f4769f9bdb7466be65088239c12046d1.eot  20.1 kB          [emitted]
|         448c34a56d699c29117adc64c43affeb.woff2    18 kB          [emitted]
|          fa2772327f55d8198301fdb8bcfc8158.woff  23.4 kB          [emitted]
|          + 2 hidden assets
|            7 modules
| npm ERR! code ELIFECYCLE
| npm ERR! errno 2
| npm ERR! openbmc_browser_interface@0.0.1 build: `rimraf dist && webpack --bail --progress --profile`
| npm ERR! Exit status 2
| npm ERR!
| npm ERR! Failed at the openbmc_browser_interface@0.0.1 build script.
| npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
| 
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /gsa/ausgsa/home/b/m/bmcbuild/.npm/_logs/2018-05-21T21_08_10_080Z-debug.log
| WARNING: /home/bmcbuild/releases/obmc910/Builds/ob910.1821.20180521c/86add116627980d099ac9a80c14970a754f10c85/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/temp/run.do_compile.6828:1 exit 2 from 'npm run-script build'
| ERROR: Function failed: do_compile (log file is located at /home/bmcbuild/releases/obmc910/Builds/ob910.1821.20180521c/86add116627980d099ac9a80c14970a754f10c85/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/temp/log.do_compile.6828)
NOTE: recipe phosphor-webui-1.0-r0: task do_compile: Failed
```

**Comment by gtmills** [comment]
Commits that passed before are now failing, a problem with a package going End of Life?

**Comment by gtmills** [comment]
Removing the `$HOME/.npm` dir did not help. More than 1 person has hit this now.

**Comment by gtmills** [comment]
A debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin/node',
1 verbose cli   '/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'build' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle openbmc_browser_interface@0.0.1~prebuild: openbmc_browser_interface@0.0.1
6 info lifecycle openbmc_browser_interface@0.0.1~build: openbmc_browser_interface@0.0.1
7 verbose lifecycle openbmc_browser_interface@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle openbmc_browser_interface@0.0.1~build: PATH: /tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/bin/node-gyp-bin:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/git/node_modules/.bin:/esw/san5/gmills/obmc/openbmc/scripts:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin/allarch-openbmc-linux:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/sbin:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/sbin:/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/bin:/esw/san5/gmills/obmc/openbmc/import-layers/yocto-poky/bitbake/bin:/tmp/gmills/build/tmp/hosttools
9 verbose lifecycle openbmc_browser_interface@0.0.1~build: CWD: /tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/git
10 silly lifecycle openbmc_browser_interface@0.0.1~build: Args: [ '-c', 'rimraf dist && webpack --bail --progress --profile' ]
11 silly lifecycle openbmc_browser_interface@0.0.1~build: Returned: code: 2  signal: null
12 info lifecycle openbmc_browser_interface@0.0.1~build: Failed to exec build script
13 verbose stack Error: openbmc_browser_interface@0.0.1 build: `rimraf dist && webpack --bail --progress --profile`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid openbmc_browser_interface@0.0.1
15 verbose cwd /tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/git
16 verbose Linux 3.10.0-693.2.2.el7.x86_64
17 verbose argv "/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin/node" "/tmp/gmills/build/tmp/work/all-openbmc-linux/phosphor-webui/1.0-r0/recipe-sysroot-native/usr/bin/npm" "run-script" "build"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 2
22 error openbmc_browser_interface@0.0.1 build: `rimraf dist && webpack --bail --progress --profile`
22 error Exit status 2
23 error Failed at the openbmc_browser_interface@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

```
