### ISSUE TITLE
sync_inventory_items.py[858]: NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by geissonator** [openbmc/openbmc#641]
Seeing this in boot up on barreleye with latest master (02da4558)

Looks to me like the file just needs an import of os.  There's a few other nuggets in the logs so not positive it's this or not, but we're not getting to BMC_READY (stuck at BMC_STARTING)

```
Sep 20 21:25:15 barreleye sync_inventory_items.py[859]: Traceback (most recent call last):
Sep 20 21:25:15 barreleye sync_inventory_items.py[859]:   File "/usr/sbin/sync_inventory_items.py", line 115, in <module>
Sep 20 21:25:15 barreleye sync_inventory_items.py[859]:     inventory = os.path.join(
Sep 20 21:25:15 barreleye sync_inventory_items.py[859]: NameError: name 'os' is not defined
Sep 20 21:25:15 barreleye sync_inventory_items.py[858]: Traceback (most recent call last):
Sep 20 21:25:15 barreleye sync_inventory_items.py[858]:   File "/usr/sbin/sync_inventory_items.py", line 115, in <module>
Sep 20 21:25:15 barreleye sync_inventory_items.py[858]:     inventory = os.path.join(
Sep 20 21:25:15 barreleye sync_inventory_items.py[858]: NameError: name 'os' is not defined
```

**Comment by bradbishop** [comment]
oops.
