### ISSUE TITLE
Palmetto host shows no console output, chassis_control.py backtraces during poweron

### ISSUE THREAD

**Issue by amboar** [openbmc/openbmc#819]
The host state fails to transition out of HOST_POWERED_ON on palm5 running a clean build of 730ecb841df9eace1febaf5ade7cff66ff18c583. There's no console output from the host, and a backtrace appears in some of the system state management code in `chassis_control.py`:

```
Nov 20 23:55:06 palmetto chassis_control.py[679]: ERROR:dbus.connection:Exception in handler for D-Bus signal:
Nov 20 23:55:06 palmetto chassis_control.py[679]: Traceback (most recent call last):
Nov 20 23:55:06 palmetto chassis_control.py[679]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 230, in maybe_handle_message
Nov 20 23:55:06 palmetto chassis_control.py[679]:     self._handler(*args, **kwargs)
Nov 20 23:55:06 palmetto chassis_control.py[679]:   File "/usr/sbin/chassis_control.py", line 180, in SystemStateHandler
Nov 20 23:55:06 palmetto chassis_control.py[679]:     intf.Set("org.openbmc.settings.Host", "system_state", state_name)
Nov 20 23:55:06 palmetto chassis_control.py[679]:   File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
Nov 20 23:55:06 palmetto chassis_control.py[679]:     **keywords)
Nov 20 23:55:06 palmetto chassis_control.py[679]:   File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
Nov 20 23:55:06 palmetto chassis_control.py[679]:     message, timeout)
Nov 20 23:55:06 palmetto chassis_control.py[679]: DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "Set" with signature "sss" on interface "org.freedesktop.DBus.Properties" doesn't exist
```

I've captured [the full journalctl output](https://github.com/openbmc/openbmc/files/602454/journal.txt)

**Comment by geissonator** [comment]
Anything suspicious in the host setting service?  "systemctl status org.openbmc.settings.Host.service | cat"
